### ISSUE TITLE
Repartir las clases para los integrantes

### ISSUE THREAD

**Issue by 0rcan** [0rcan/MiniProyecto1_S3#4]

**Comment by 0rcan** [comment]
Chicos ustedes eligen sus ramas diego elije 3 y albert 2

yo elijo: app.java, soldado.java y soldadoraso.java
siuuuu

**Comment by diego-11** [comment]
me parece bien, entonces yo escojo las clases, Rango, OperacionesMilitares, Coronel

**Comment by A75TD** [comment]
escojo Capitán y Teniente
